### ISSUE TITLE
npm ui:add <component> --  command runs into error. Issue with generateIndex.mts script

### ISSUE THREAD

**Issue by webstar-code** [dan5py/turborepo-shadcn-ui#16]
![image](https://github.com/dan5py/turborepo-shadcn-ui/assets/60955315/74c8e373-8e43-42e4-9e24-0ea77dad8b6f)

I tried adding another component, the component was added successfully, but then it ran into error while running this script.
Event though the new alert component is added, when using it in the app, i cannot see the component

![image](https://github.com/dan5py/turborepo-shadcn-ui/assets/60955315/7a086c61-ff53-4181-8db5-d91874e4fe46)

**Comment by dan5py** [comment]
Hi @webstar-code, I removed the `generateIndex` script in the `1.0.3` release (https://github.com/dan5py/turborepo-shadcn-ui/commit/9f51459b973ac9016df23d09bf67088eb98c041c). You can delete the the `postui:add` script in the `package.json` of the `ui` package, and the error should disappear. I also suggest you to update the other files since I made some changes.
